[project]
name = "pytest-exasol-slc"
version = "1.0.1"
description = ""
authors = [{ name = "Mikhail Beck", email = "mikhail.beck@exasol.com" }]
# Restrict Python versions as difficulty with some unit tests related
# to the ParallelTask implementation for Python 3.14.
# This will be resolved in:
#    https://github.com/exasol/pytest-slc/issues/4
requires-python = ">=3.10,<3.14"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "pytest>=9,<10",
    "pytest-exasol-backend>=1.1, <2",
    "pytest-exasol-extension>=0.2.4, <2",
    "exasol-python-extension-common>=0.9.0, <1.0.0",
    "exasol-saas-api>=2.8,<3",
]

[project.entry-points.pytest11]
slc = "exasol.pytest_slc"

[dependency-groups]
dev = [
    "exasol-toolbox>=10.0.0,<11",
    "exasol-bucketfs>=1.0.0",
]

[tool.poetry]
requires-poetry = ">=2.3.0"
packages = [{include = "exasol"}]

[build-system]
requires = ["poetry_core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
relative_files = true
source = [
    "exasol",
]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.coverage.report]
fail_under = 15

[tool.black]
line-length = 88
verbose = false
include = "\\.pyi?$"

[tool.isort]
profile = "black"
force_grid_wrap = 2

[tool.pylint.master]
fail-under = 6.1
output-format = "colorized,json:.lint.json,text:.lint.txt"

[tool.pylint.format]
max-line-length = 88
max-module-lines = 800

[tool.ruff.lint]
extend-ignore = [
    "E",  # Syntax errors
    "F",  # Pyflakes rules (excluding F401)
    "UP", # pyupgrade rules
    "D",  # Docstring rules
]
extend-select = ["F401"]
unfixable = []

[[tool.mypy.overrides]]
module = [
    "test.unit.*",
    "test.integration.*",
]
ignore_errors = true
ignore_missing_imports = true

[tool.sonar]
projectKey = "com.exasol:pytest-slc"
host.url = "https://sonarcloud.io"
organization = "exasol"
