name: Slow Checks

on:
  workflow_call:

jobs:

  pytester-tests:
    name: Pytester
    uses: ./.github/workflows/tests-onprem-pytester.yml
    permissions:
      read

  ordinary-itests:
    name: Ordinary
    # runs the integration tests without `pytester`
    uses: ./.github/workflows/tests-onprem-ordinary.yml
    permissions:
      read
